[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  # Serve a versão completa da imagem
  from = "/images/full/*"
  to = "/.netlify/images?url=/images/:splat&quality=100"
  status = 200

[[redirects]]
  # Serve uma versão redimensionada da imagem
  from = "/images/:width/*"
  to = "/.netlify/images?url=/images/:splat&width=:width&quality=100"
  status = 200